### REQUEST PRUEBA 
GET http://localhost:4000/ 

### REQUEST REGISTER
POST http://localhost:4000/auth/signup
Content-Type: application/json

{
    "name": "Victoria Nieto", 
    "email": "marianieto29@gmail.com",
    "username": "mariavnn22",
    "age": 18,
    "password": "12345678",
    "confirmPassword": "12345678"
}

### REQUEST LOGIN
POST http://localhost:4000/auth/signin
Content-Type: application/json

{
    "username": "mariavnn22",
    "password": "12345678"
}

### REQUEST DATOS DE MI USUARIO
GET http://localhost:4000/auth/me


### REQUEST UPDATE DATOS DE MI USUARIO
PATCH http://localhost:4000/auth/me/update
Content-Type: application/json

{
    "name" : "Maria Nieto"
}


### SEARCH BOOKS
GET http://localhost:4000/book/search?q=harry+potter

### ADD BOOK TO READING LIST 
POST http://localhost:4000/book/add-reading-list
Content-Type: application/json

{
  "googleId": "abYKXvCwEToC",
  "volumenInfo": {
    "title": "Harry Potter",
    "subtitle": "The Story of a Global Business Phenomenon",
    "authors": ["S. Gunelius"],
    "publisher": "Springer",
    "publishedDate": "2008-06-03",
    "description": "The Harry Potter books are the bestselling books of all time. In this fascinating study, Susan Gunelius analyzes every aspect of the brand phenomenon that is Harry Potter. Delving into price wars, box office revenue, and brand values, amongst other things, this is the story of the most incredible brand success there has ever been.",
    "imageLinks": {
      "smallThumbnail": "http://books.google.com/books/content?id=abYKXvCwEToC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
      "thumbnail": "http://books.google.com/books/content?id=abYKXvCwEToC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
    }
  }
}

### GET READING LIST FROM USER
GET http://localhost:4000/book/reading-list

### POST REVIEW BOOK POST 
POST http://localhost:4000/book/post 
Content-Type: application/json

{
  "googleId": "abYKXvCwEToC",
  "volumenInfo": {
    "title": "Harry Potter",
    "subtitle": "The Story of a Global Business Phenomenon",
    "authors": ["S. Gunelius"],
    "publisher": "Springer",
    "publishedDate": "2008-06-03",
    "description": "The Harry Potter books are the bestselling books of all time. In this fascinating study, Susan Gunelius analyzes every aspect of the brand phenomenon that is Harry Potter. Delving into price wars, box office revenue, and brand values, amongst other things, this is the story of the most incredible brand success there has ever been.",
    "imageLinks": {
      "smallThumbnail": "http://books.google.com/books/content?id=abYKXvCwEToC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
      "thumbnail": "http://books.google.com/books/content?id=abYKXvCwEToC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
    }
  },
  "review": "Un libro fascinante que captura la magia desde la primera página."
}